version: 2.1

orbs:
  node: circleci/node@7.0.0
jobs:
  build_and_deploy_mainnet:
    resource_class: large
    docker:
      - image: 'cimg/node:20.19'
    environment:
      DEPLOY_HOST: 34.53.102.108
      DEPLOY_FOLDER: scan-meter-io
      SSH_OPTIONS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:48o4O3yWCP1MbjxhyGvDL+NNUsYcRJVodZjzg7nV0C4"
      - run:
          name: install rsync
          command: |
            sudo apt-get update 
            sudo apt-get install -y rsync
      - checkout
      - restore_cache:
          key: scanv2-deps-{{ checksum "package.json" }}
      - run:
          name: install npm dependencies
          command: npm install --force
      - save_cache:
          key: scanv2-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: copy config.json
          command: cp src/config-example.json src/config.json
      - run:
          name: production build
          command: NODE_ENV=production VUE_APP_CHAIN_ID=82 npm run build
      - run:
          name: deploy
          command: |
            rsync -e "ssh $SSH_OPTIONS" -rzvh --delete ./dist/ root@$DEPLOY_HOST:/var/www/$DEPLOY_FOLDER/
            ssh $SSH_OPTIONS root@$DEPLOY_HOST "service nginx restart"

  build_and_deploy_testnet:
    resource_class: large
    docker:
      - image: 'cimg/node:16.7'
    environment:
      DEPLOY_HOST: 34.53.102.108
      DEPLOY_FOLDER: scan-testnet-meter-io
      SSH_OPTIONS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:48o4O3yWCP1MbjxhyGvDL+NNUsYcRJVodZjzg7nV0C4"
      - run:
          name: install rsync
          command: |
            sudo apt-get update 
            sudo apt-get install -y rsync
      - checkout
      - restore_cache:
          key: scanv2-deps-{{ checksum "package.json" }}
      - run:
          name: install npm dependencies
          command: npm install
      - save_cache:
          key: scanv2-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: copy config.json
          command: cp src/config-example.json src/config.json
      - run:
          name: testnet build
          command: VUE_APP_CHAIN_ID=83 npm run build
      - run:
          name: deploy
          command: |
            rsync -e "ssh $SSH_OPTIONS" -rzvh --delete ./dist/ root@$DEPLOY_HOST:/var/www/$DEPLOY_FOLDER/
            ssh $SSH_OPTIONS root@$DEPLOY_HOST "service nginx restart"

workflows:
  fresh_deploy:
    jobs:
      - build_and_deploy_testnet:
          filters:
            branches:
              only:
                - master
      - build_and_deploy_mainnet:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
