version: 2.1

orbs:
  node: circleci/node@4.7.0
jobs:
  build_and_deploy_mainnet:
    resource_class: large
    docker:
      - image: 'cimg/node:16.7'
    steps:
      - checkout
      - run:
          name: download & unzip awscli v2
          command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip
      - run:
          name: install awscli v2
          command: sudo ./aws/install
      # look for existing cache and restore if found
      - restore_cache:
          key: scanv2-deps-{{ checksum "package.json" }}
      - run:
          name: install npm dependencies
          command: npm install
      - save_cache:
          key: scanv2-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: copy config.json
          command: cp src/config-example.json src/config.json
      - run:
          name: production build
          command: NODE_ENV=production VUE_APP_CHAIN_ID=82 npm run build
      - run:
          name: s3 sync
          command: aws s3 sync ./dist/ s3://scan.meter.io/ --delete
      - run:
          name: invalidation
          command: aws cloudfront create-invalidation --distribution-id E3H3GGDPKC4QWP --paths "/*"

  build_and_deploy_testnet:
    resource_class: large
    docker:
      - image: 'cimg/node:16.7'
    steps:
      - checkout
      - run:
          name: download & unzip awscli v2
          command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip
      - run:
          name: install awscli v2
          command: sudo ./aws/install
      - restore_cache:
          key: scanv2-deps-{{ checksum "package.json" }}
      - run:
          name: install npm dependencies
          command: npm install
      - save_cache:
          key: scanv2-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: copy config.json
          command: cp src/config-example.json src/config.json
      - run:
          name: testnet build
          command: VUE_APP_CHAIN_ID=83 npm run build
      - run:
          name: s3 sync
          command: aws s3 sync ./dist/ s3://scan-testnet.meter.io/ --delete
      - run:
          name: invalidation
          command: aws cloudfront create-invalidation --distribution-id E2M101IOX22Z2Q --paths "/*"

workflows:
  fresh_deploy:
    jobs:
      - build_and_deploy_testnet:
          context: aws-2023
          filters:
            branches:
              only:
                - master
      - build_and_deploy_mainnet:
          context: aws-2023
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
